### ISSUE TITLE
Categorise by year and type

### ISSUE THREAD

**Issue by marioa** [softwaresaved/CW-ideas#12]

**Comment by marioa** [comment]
@shoaibsufi is this what you wanted?

* https://softwaresaved.github.io/CW-ideas/byyear/

**Comment by shoaibsufi** [comment]
Hi Mario,

Thanks.

That’s much closer – worth a discussion.

Best
Shoaib

From: Mario Antonioletti ***@***.***>
Date: Sunday, 13 November 2022 at 12:12
To: softwaresaved/CW-ideas ***@***.***>
Cc: Shoaib Ahmed Sufi ***@***.***>, Mention ***@***.***>
Subject: Re: [softwaresaved/CW-ideas] Categorise by year and type (Issue #12)

@shoaibsufi<https://github.com/shoaibsufi> is this what you wanted?

  *   https://softwaresaved.github.io/CW-ideas/byyear/

**Comment by marioa** [comment]
Closing this issue. Further discussion will lead to a new issue - do not want feature creep on this issue.
